/* ==========================================================================
   DEPTH//LAB — effect modules (what the playground panel is built from),
   the image library, and the recommended recipes.
   ========================================================================== */
import {DEFAULTS} from './engine.js';

export const LIBRARY=[
  {id:'01',name:'COLD BREW',src:'../images/01.jpg',depth:'../images/01-depth.png'},
  {id:'02',name:'CLOUD FOREST',src:'../images/02.webp',depth:'../images/02-depth.png'},
  {id:'03',name:'CLOUD PEAK',src:'../images/03.webp',depth:'../images/03-depth.png'},
  {id:'04',name:'FIELD OPERATOR',src:'../images/04.jpg',depth:'../images/04-depth.png',edge:2.6},
];

/* param: {k, label, min, max, step} | {k, label, opts:[...]} (select, stores the index unless `str`) | {k,label,text:true} | {k,label,check:true} */
export const FX=[
  {id:'base',n:'00',name:'RELIEF / CAMERA',on:null,
   what:'THE BASE 3D. THE DEPTH MAP PUSHES THE IMAGE INTO RELIEF. DRAG THE STAGE TO ORBIT, WHEEL TO ZOOM, SHIFT-DRAG TO PAN, DOUBLE-CLICK TO RESET.',
   use:'EVERYTHING ELSE SITS ON TOP OF THIS. MESH = CLEAN PHOTO. POINTS = PIXEL FIELD.',
   params:[{k:'geometry',label:'GEOMETRY',opts:['mesh','points'],str:true},{k:'relief',label:'RELIEF',min:0,max:1.4},{k:'fill',label:'POINT SIZE',min:.3,max:1.6},{k:'round',label:'ROUND POINTS',check:true},
     {k:'sway',label:'AUTO SWAY',min:0,max:1.5},{k:'swaySpeed',label:'SWAY SPEED',min:.1,max:3},{k:'zoom',label:'ZOOM',min:.5,max:8},{k:'yaw',label:'YAW',min:-.8,max:.8},{k:'pitch',label:'PITCH',min:-.55,max:.55}]},
  {id:'focus',n:'01',name:'RACK FOCUS',on:'focusOn',
   what:'DEPTH OF FIELD. EVERYTHING AWAY FROM THE FOCAL PLANE BLURS, LIKE A FAST LENS. WITH FOLLOW ON, FOCUS PULLS TO WHATEVER IS UNDER THE CURSOR.',
   use:'DIRECTS THE EYE. PULL FOCUS ON SCROLL FROM FOREGROUND TO SUBJECT.',
   params:[{k:'focusFollow',label:'FOLLOW CURSOR',check:true},{k:'focus',label:'FOCAL PLANE',min:0,max:1},{k:'aperture',label:'APERTURE',min:0,max:8}]},
  {id:'scan',n:'02',name:'SCAN REVEAL',on:'scanOn',
   what:'THE IMAGE MATERIALISES NEAR TO FAR BEHIND A RED RANGE SWEEP, LIKE A LIDAR PASS. SET AUTO TO 0 TO DRIVE IT BY HAND.',
   use:'PAGE LOAD OR SECTION ENTER.',
   params:[{k:'scanAuto',label:'AUTO SPEED',min:0,max:1},{k:'scan',label:'POSITION',min:0,max:1},{k:'scanBand',label:'BAND WIDTH',min:.005,max:.12}]},
  {id:'light',n:'03',name:'RELIGHT',on:'lightOn',
   what:'SURFACE NORMALS ARE DERIVED FROM THE DEPTH MAP, SO A NEW LIGHT CAN RAKE ACROSS A FLAT PHOTO. MOVE THE CURSOR: THE LIGHT FOLLOWS.',
   use:'PRODUCT AND PORTRAIT PLATES. LOW AMBIENT = DRAMATIC.',
   params:[{k:'lightFollow',label:'FOLLOW CURSOR',check:true},{k:'light',label:'AMOUNT',min:0,max:1},{k:'ambient',label:'AMBIENT',min:0,max:1},{k:'lightH',label:'LIGHT HEIGHT',min:.05,max:1.2},{k:'spec',label:'SPECULAR',min:0,max:1},{k:'lightWarm',label:'WARMTH',min:0,max:1},{k:'lightX',label:'LIGHT X',min:0,max:1},{k:'lightY',label:'LIGHT Y',min:0,max:1}]},
  {id:'fog',n:'04',name:'DEPTH FOG',on:'fogOn',
   what:'ANIMATED MIST PLACED BETWEEN THE DEPTH LAYERS. NEAR OBJECTS STAY CLEAR, DISTANCE FILLS IN AND DRIFTS.',
   use:'LANDSCAPES. MAKES LAYERS READ AND ADDS SLOW LIFE TO A STILL.',
   params:[{k:'fog',label:'DENSITY',min:0,max:1},{k:'fogNear',label:'STARTS AT',min:0,max:1},{k:'fogFar',label:'FULL AT',min:0,max:1},{k:'fogSpeed',label:'DRIFT',min:0,max:2},{k:'fogTone',label:'TONE (DARK-LIGHT)',min:0,max:1}]},
  {id:'dissolve',n:'05',name:'PARTICLE DISSOLVE / MORPH',on:'dissolveOn',
   what:'EVERY PIXEL BECOMES A PARTICLE THAT LIFTS OFF AND DRIFTS. MORPH BLENDS COLOUR AND DEPTH TOWARD IMAGE B (PICK B IN THE IMAGE STRIP). BEST WITH GEOMETRY = POINTS.',
   use:'TRANSITIONS BETWEEN PLATES: DISSOLVE UP, MORPH, DISSOLVE DOWN.',
   params:[{k:'dissolve',label:'DISSOLVE',min:0,max:1},{k:'turb',label:'TURBULENCE',min:0,max:1.2},{k:'wind',label:'WIND',min:-1,max:1},{k:'morph',label:'MORPH A > B',min:0,max:1}]},
  {id:'text',n:'06',name:'DEPTH TYPE',on:'textOn',
   what:'HEADLINE TYPE PLACED AT A REAL DEPTH INSIDE THE SCENE. ANYTHING NEARER THAN THE TYPE COVERS IT, ANYTHING FARTHER SITS BEHIND IT. SLIDE DEPTH TO THREAD IT THROUGH THE LAYERS.',
   use:'PLATE TITLES. THE STRONGEST MATCH FOR THE BRUTALIST TYPE.',
   params:[{k:'text',label:'TEXT',text:true},{k:'textDepth',label:'DEPTH',min:0,max:1},{k:'textSize',label:'SIZE',min:.05,max:.9},{k:'textY',label:'VERTICAL',min:0,max:1},{k:'textColor',label:'COLOUR',opts:['WHITE','RED','BLACK']}]},
  {id:'slit',n:'07',name:'SLIT-SCAN',on:'slitOn',
   what:'EACH ROW, COLUMN OR DEPTH LAYER FOLLOWS THE CAMERA WITH ITS OWN DELAY, SO MOTION SMEARS AND CATCHES UP. NEEDS MOVEMENT: ORBIT THE STAGE OR RAISE AUTO SWAY.',
   use:'MECHANICAL, GLITCHY ENERGY ON FAST SCROLL OR HOVER.',
   params:[{k:'slit',label:'DELAY',min:0,max:1},{k:'slitAxis',label:'AXIS',opts:['ROWS','COLUMNS','DEPTH']}]},
  {id:'sort',n:'08A',name:'PIXEL SORT',on:'sortOn',
   what:'BRIGHT RUNS OF PIXELS SMEAR INTO STREAKS ALONG ONE DIRECTION. THRESHOLD DECIDES HOW MUCH OF THE IMAGE MELTS.',
   use:'DEGRADED TRANSITIONS, HOVER STATES.',
   params:[{k:'sortThr',label:'THRESHOLD',min:.05,max:.95},{k:'sortLen',label:'LENGTH',min:0,max:1},{k:'sortDir',label:'DIRECTION',opts:['DOWN','LEFT','UP','RIGHT']}]},
  {id:'mosh',n:'08B',name:'DATAMOSH',on:'moshOn',
   what:'RANDOM BLOCKS REFUSE TO UPDATE AND DRAG THE PREVIOUS FRAME ALONG WITH THE CAMERA MOTION, LIKE A CORRUPTED VIDEO. NEEDS MOVEMENT.',
   use:'SIGNAL-LOSS MOMENTS BETWEEN SECTIONS.',
   params:[{k:'mosh',label:'AMOUNT',min:0,max:.95},{k:'moshBlock',label:'BLOCK SIZE',min:6,max:80,step:1}]},
  {id:'lens',n:'09',name:'INSPECTION LENS',on:'lensOn',
   what:'A WINDOW UNDER THE CURSOR THAT READS THE SAME PIXELS ANOTHER WAY: DEPTH HEATMAP, WIREFRAME, SURFACE NORMALS, RAW DEPTH OR CONTOURS.',
   use:'AN INTERACTIVE INSPECTOR. SHOWS VISITORS HOW THE PLATE IS BUILT.',
   params:[{k:'lensMode',label:'MODE',opts:['HEAT','WIREFRAME','NORMALS','DEPTH','CONTOURS']},{k:'lensR',label:'RADIUS',min:.05,max:.6},{k:'lensFollow',label:'FOLLOW CURSOR',check:true}]},
  {id:'contour',n:'10',name:'CONTOURS',on:'contourOn',
   what:'DEPTH DRAWN AS ELEVATION LINES THAT TRAVEL THROUGH THE SCENE. EVERY FIFTH LINE IS RED. DIM IMAGE TURNS THE PHOTO INTO A SURVEY MAP.',
   use:'MOUNTAIN AND TERRAIN PLATES, LOADING STATES.',
   params:[{k:'contour',label:'AMOUNT',min:0,max:1},{k:'contourN',label:'LINE COUNT',min:4,max:80,step:1},{k:'contourSpeed',label:'TRAVEL',min:0,max:.5},{k:'contourDim',label:'DIM IMAGE',min:0,max:1}]},
  {id:'finish',n:'F',name:'FINISH: DITHER / MONO / SCANLINES',on:'ditherOn',
   what:'THE BRUTALIST DISTORTION FROM THE MAIN SITE: LOW BIT-DEPTH ORDERED DITHER, PHOSPHOR MONO, CRT SCANLINES. THE TOGGLE CONTROLS DITHER; MONO AND SCANLINES ARE ALWAYS LIVE.',
   use:'LAYER OVER ANY OTHER EFFECT TO KEEP IT ON-BRAND.',
   params:[{k:'dither',label:'DITHER',min:0,max:1},{k:'ditherLv',label:'LEVELS',min:2,max:16,step:1},{k:'mono',label:'MONO',min:0,max:1},{k:'scanlines',label:'SCANLINES',min:0,max:1}]},
  {id:'gyro',n:'11',name:'GYROSCOPE PARALLAX',on:'gyroOn',
   what:'ON A PHONE, TILTING THE DEVICE SHIFTS THE CAMERA. ON DESKTOP THERE IS NO SENSOR: USE AUTO SWAY TO PREVIEW THE FEEL. iOS ONLY ALLOWS THE SENSOR OVER HTTPS.',
   use:'MOBILE. THE PAGE BECOMES A WINDOW.',params:[]},
  {id:'video',n:'12',name:'VIDEO HANDOFF',on:'videoOn',
   what:'LOAD A SHORT CLIP OF THE SAME FRAME ( + VIDEO ). HANDOFF CROSSFADES THE STILL INTO THE MOVING CLIP WHILE THE RELIEF FLATTENS, SO THE PHOTO COMES ALIVE.',
   use:'THE END OF A DOLLY. NEEDS A CLIP THAT STARTS ON THE STILL.',
   params:[{k:'videoMix',label:'HANDOFF',min:0,max:1}]},
];

/* ---------------------------------------------------------------- recipes */
const clamp=(x,a,b)=>Math.min(b,Math.max(a,x)),lerp=(a,b,t)=>a+(b-a)*t;
const seg=(t,a,b)=>{const x=clamp((t-a)/(b-a),0,1);return x*x*(3-2*x)},bump=t=>Math.sin(Math.PI*clamp(t,0,1));
const BASE={...DEFAULTS,sway:.25,focusFollow:0,lightFollow:0,lensFollow:0,scanAuto:0};

/* at(t): t is scroll progress 0..1 through the section; returns the full state for that moment */
export const RECIPES=[
  {id:'directed',n:'R01',name:'DIRECTED PLATE',fx:['02 SCAN','01 FOCUS','06 TYPE'],where:'SECTION ENTER > HOLD',image:'04',
   why:'THE ONE I WOULD SHIP FIRST. THE PLATE SCANS IN, THE TITLE IS ALREADY THREADED BEHIND HIS HANDS AND THE CAMERA, THEN FOCUS PULLS FROM THE NEAR LEAF TO THE OPERATOR WHILE THE CAMERA PUSHES IN. THREE EFFECTS, ONE DIRECTED SHOT.',
   at:t=>({...BASE,scanOn:t<.4?1:0,scan:lerp(0,1.15,seg(t,0,.36)),relief:lerp(.15,.7,seg(t,.1,.5)),yaw:lerp(0,.22,seg(t,.2,.7)),pitch:-.04*seg(t,.2,.7),
     zoom:lerp(1,2.1,seg(t,.5,1)),cx:-.08*seg(t,.5,1),cy:.03*seg(t,.5,1),focusOn:1,aperture:lerp(0,3.5,seg(t,.3,.5)),focus:lerp(.92,.56,seg(t,.5,.85)),
     textOn:1,text:'OPERATOR',textDepth:.6,textSize:.11,textY:.6,textColor:0})},
  {id:'product',n:'R02',name:'PRODUCT HERO',fx:['03 RELIGHT','01 FOCUS'],where:'HERO / PRODUCT SECTION',image:'01',
   why:'A LIGHT SWEEPS ACROSS THE CAN AND FACE WHILE A SHALLOW FOCAL PLANE HOLDS ON THE PRODUCT. ON THE REAL PAGE THE LIGHT FOLLOWS THE CURSOR; HERE IT TRAVELS WITH THE SCROLL.',
   at:t=>({...BASE,relief:.55,sway:.35,zoom:lerp(1.15,1.6,seg(t,0,1)),cx:-.1,cy:.02,lightOn:1,light:1,ambient:lerp(.1,.3,t),lightH:.3,spec:.6,lightWarm:.6,lightX:lerp(.1,.75,seg(t,0,1)),lightY:lerp(.65,.3,seg(t,0,1)),
     focusOn:1,focus:.94,aperture:lerp(1,4,seg(t,.2,.8))})},
  {id:'survey',n:'R03',name:'SURVEY MAP',fx:['10 CONTOURS','04 FOG','09 LENS'],where:'LANDSCAPE PLATES',image:'03',
   why:'THE PHOTO ARRIVES AS A CONTOUR SURVEY, THE LINES DRAIN AWAY TO REVEAL THE IMAGE, FOG SETTLES BETWEEN THE RIDGES, AND A HEAT LENS STAYS AVAILABLE FOR INSPECTION.',
   at:t=>({...BASE,relief:lerp(.3,.9,seg(t,0,.6)),yaw:lerp(-.2,.2,t),pitch:.06,zoom:lerp(1,1.5,seg(t,.4,1)),contourOn:1,contour:lerp(1,0,seg(t,.3,.75)),contourDim:lerp(.9,0,seg(t,.2,.6)),contourN:30,contourSpeed:.1,
     fogOn:1,fog:lerp(0,.75,seg(t,.35,.9)),fogNear:.3,fogFar:.95,fogSpeed:.5,lensOn:t>.55?1:0,lensMode:0,lensR:.17,lensX:lerp(.3,.7,seg(t,.55,1)),lensY:.42})},
  {id:'disintegrate',n:'R04',name:'DISINTEGRATION CUT',fx:['05 DISSOLVE','05 MORPH','08A SORT'],where:'TRANSITION BETWEEN PLATES',image:'01',B:'02',
   why:'THE OUTGOING PLATE LIFTS OFF AS PARTICLES, STREAKS AT ITS BRIGHTEST EDGES, AND THE SAME PARTICLES SETTLE INTO THE NEXT IMAGE. ONE CONTINUOUS OBJECT INSTEAD OF A CUT.',
   at:t=>({...BASE,geometry:'points',fill:1.15,relief:.7,sway:.4,yaw:lerp(-.15,.15,t),dissolveOn:1,dissolve:bump(seg(t,.12,.88))*.62,turb:.5,wind:.35,morph:seg(t,.38,.62),
     sortOn:t>.2&&t<.8?1:0,sortThr:lerp(.95,.45,bump(seg(t,.2,.8))),sortLen:.7,sortDir:0})},
  {id:'signal',n:'R05',name:'SIGNAL LOSS',fx:['07 SLIT-SCAN','08B DATAMOSH','F DITHER'],where:'GLITCH BEAT / FAST SCROLL',image:'02',
   why:'THE MOST AGGRESSIVE ONE. CAMERA MOTION SMEARS ROW BY ROW, BLOCKS OF THE FRAME STICK AND DRAG, AND THE DITHER HOLDS IT IN THE BRUTALIST WORLD. USE IT BRIEFLY.',
   at:t=>({...BASE,relief:.8,sway:lerp(.4,1.4,bump(t)),swaySpeed:lerp(.8,2.6,bump(t)),slitOn:1,slit:bump(t)*.9,slitAxis:0,moshOn:1,mosh:bump(seg(t,.2,.8))*.55,moshBlock:28,
     ditherOn:1,dither:.85,ditherLv:4,scanlines:.6})},
  {id:'lidar',n:'R06',name:'LIDAR BOOT',fx:['02 SCAN','POINTS','10 CONTOURS','F DITHER'],where:'PAGE LOAD',image:'02',
   why:'THE FIRST THING A VISITOR SEES: A MONOCHROME POINT CLOUD SCANS IN WITH SURVEY LINES, THEN COLOUR AND DENSITY ARRIVE AND IT RESOLVES INTO THE PHOTOGRAPH.',
   at:t=>({...BASE,geometry:'points',fill:lerp(.85,1.15,seg(t,.5,1)),relief:lerp(1.1,.6,seg(t,.5,1)),yaw:lerp(-.35,0,seg(t,.2,1)),pitch:lerp(.12,0,seg(t,.2,1)),scanOn:t<.55?1:0,scan:lerp(0,1.15,seg(t,0,.5)),scanBand:.04,
     contourOn:1,contour:lerp(.7,0,seg(t,.45,.8)),contourDim:.3,mono:lerp(1,0,seg(t,.5,.85)),ditherOn:1,dither:lerp(.9,.0,seg(t,.6,1)),ditherLv:4,scanlines:lerp(.8,0,seg(t,.6,1))})},
  {id:'living',n:'R07',name:'LIVING STILL',fx:['01 FOCUS','DOLLY','12 VIDEO'],where:'FINALE OF A PLATE',image:'04',needsVideo:true,
   why:'THE CAMERA PUSHES IN, FOCUS SETTLES, AND AT FULL ZOOM THE STILL HANDS OFF TO A SHORT CLIP OF THE SAME FRAME. LOAD A CLIP WITH + VIDEO TO SEE THE LAST THIRD; WITHOUT ONE THE RECIPE STOPS AT THE PUSH-IN.',
   at:t=>({...BASE,relief:lerp(.7,.5,seg(t,.6,1)),sway:lerp(.3,0,seg(t,.6,.9)),yaw:lerp(.2,0,seg(t,.3,.8)),zoom:lerp(1,2.2,seg(t,0,.75)),cx:-.08*seg(t,0,.75),cy:.03*seg(t,0,.75),
     focusOn:1,focus:.56,aperture:lerp(4,0,seg(t,.55,.8)),videoOn:1,videoMix:seg(t,.72,.95)})},
  {id:'pocket',n:'R08',name:'POCKET WINDOW',fx:['11 GYRO','04 FOG','01 FOCUS'],where:'MOBILE',image:'02',
   why:'FOR PHONES. THE PLATE ANSWERS THE TILT OF THE DEVICE, FOG DRIFTS IN THE CLEARING AND A SOFT FOCAL PLANE KEEPS IT PHOTOGRAPHIC. ON DESKTOP THE SWAY STANDS IN FOR THE SENSOR.',
   at:t=>({...BASE,relief:.85,gyroOn:1,sway:1.1,swaySpeed:.9,zoom:lerp(1.1,1.4,t),fogOn:1,fog:.55,fogNear:.35,fogFar:.9,fogSpeed:.6,focusOn:1,focus:lerp(.92,.25,t),aperture:2.2})},
  {id:'xray',n:'R09',name:'X-RAY INSPECTOR',fx:['09 LENS','ZOOM'],where:'INTERACTIVE DETAIL VIEW',image:'01',
   why:'A LENS SWEEPS THE PLATE AND CYCLES THROUGH ITS READINGS: HEAT, WIREFRAME, NORMALS, CONTOURS. ON THE REAL PAGE IT FOLLOWS THE CURSOR INSIDE ENTER SPACE.',
   at:t=>({...BASE,relief:.6,sway:.3,zoom:1.25,lensOn:1,lensR:.24,lensMode:[0,1,2,4][Math.min(3,Math.floor(t*4))],lensX:.5+.28*Math.cos(t*Math.PI*2),lensY:.48+.2*Math.sin(t*Math.PI*2)})},
  {id:'threaded',n:'R10',name:'THREADED TITLE',fx:['06 TYPE','04 FOG','RELIEF'],where:'PLATE TITLE CARD',image:'03',
   why:'THE PLATE NAME TRAVELS THROUGH THE SCENE FROM BEHIND THE PEAK DOWN TO THE TREELINE, SLIPPING BEHIND EACH RIDGE ON THE WAY. FOG GIVES THE LAYERS AIR.',
   at:t=>({...BASE,relief:.95,yaw:lerp(-.18,.18,t),pitch:.05,zoom:1.08,textOn:1,text:'CLOUD PEAK',textSize:.3,textY:lerp(.38,.74,seg(t,.1,.95)),textDepth:lerp(.2,.5,seg(t,.05,.95)),textColor:0,
     fogOn:1,fog:.5,fogNear:.4,fogFar:1,fogSpeed:.4})},
];
